### ISSUE TITLE
Openaire API changes?

### ISSUE THREAD

**Issue by sckott** [njahn82/ropenaire#9]
@alessiabardi

Does Openaire API use versioning?  We'd like to know if when there are changes if there's at least a changelog somewhere, and if the API has any versioning concept like in a header or something similar for major version changes?

**Comment by sckott** [comment]
any thoughts @njahn82 @alessiabardi @joschirr ?

**Comment by alessiabardi** [comment]
@sckott sorry I did not reply before. The Search API are not supporting versioning but we are not planning major changes in the parameters that can be used to query the OpenAIRE information space. 
If you noticed changes in the returned records, it is because in January we changed the data model. If you want additional details and changelist, please go to the API documentation page http://api.openaire.eu/

**Comment by sckott** [comment]
Do you keep a log of changes to the API at least?

**Comment by alessiabardi** [comment]
Changes to the interface will be reported here http://api.openaire.eu/api.html .
Since the interface hasn't changed, you won't find any changelog.

**Comment by sckott** [comment]
that's not quite what I was getting at - I was thinking if you have something like what Crossref has https://github.com/CrossRef/rest-api-doc#documentation-history - since otherwise we'd have to compare a previous version of http://api.openaire.eu/api.html to a new version to see what's changed and that's not easy

**Comment by alessiabardi** [comment]
Thanks for the clarification. So I understand that you are interested in the changelog of the documentation itself (which in fact should reflect the changes in the interface). let me add this in our TODO list.

**Comment by alessiabardi** [comment]
> let me add this in our TODO list.

Done: http://api.openaire.eu/changelog.html (linked from the bottom of the home page)

**Comment by sckott** [comment]
great, thanks very much @alessiabardi !
